"""Temporary type stub for the not-yet-ported ``drone`` package.

Only the ``ConfigParser`` surface consumed by ``interdrone`` is declared here, so
the interdrone port type-checks without pulling in the ``drone`` package (and its
``dronekit`` dependency), which lands in a later PR. Delete this stub in the PR
that ports ``drone/json_parser.py``.
"""

class ConfigParser:
    def __init__(self, config_path: str = ...) -> None: ...
    def get_self_id(self) -> int: ...
    def set_self_id(self, self_id: int) -> None: ...
    def get_drone_ids(self) -> list[str]: ...
    def get_drone_ip(self, drone_id: str) -> str | None: ...
    def get_drone_port(self, drone_id: str | int) -> str | None: ...
    def get_gs_ip(self) -> str: ...
    def get_gs_port(self) -> int: ...
    def get_speed_test_kb_data_size(self) -> int: ...
