#!/usr/bin/env bash

if g++ -L lib -I include *.c *.cpp -lfreetype -lassimp -lglfw -lGL -lm -lX11 -lpthread -lXi -lXrandr -ldl -lz -lbz2 -lpng -lbrotlidec; then
    echo compilation succeeded
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib
    ./a.out
else
    echo compilation failed
fi
